CREATE TABLE IF NOT EXISTS reservations (
  reservations_id bigserial GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id bigserial NOT NULL REFERENCES "users" ("users_id"),
  reservation_date date NOT NULL,
  reservation_time time NOT NULL,
  duration varchar(255) NOT NULL,
  people_count int NOT NULL,
  notes varchar(255),
  approval boolean,
  created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW()
);